### ISSUE TITLE
How to do/use the generateRefreshToken

### ISSUE THREAD

**Issue by jokamax** [cpjeslot/kaabar-jwt#5]
Hi,

Your library seem to use more recent of "lcobucci/jwt" package so I really want to use it.

In the README, you indicated : 
Add the methods generateJwt() and generateRefreshToken() to AuthController.php. We'll be using them in the login/refresh-token actions.

But there is no generateRefreshToken function in example nor explanation of how to use it.
Can you explain ?

Thanks,

Jonathan

**Comment by cpjeslot** [comment]
> Hi,
> 
> Your library seem to use more recent of "lcobucci/jwt" package so I really want to use it.
> 
> In the README, you indicated : Add the methods generateJwt() and generateRefreshToken() to AuthController.php. We'll be using them in the login/refresh-token actions.
> 
> But there is no generateRefreshToken function in example nor explanation of how to use it. Can you explain ?
> 
> Thanks,
> 
> Jonathan

Hello,
The README file has been changed and missing information has been added to it. 

Thank you very much for your thoughtful obversion.

Regards,
Chetan Patel
